"""add avatar and voice to user

Revision ID: d6388e3d5a94
Revises: 3f8369638ea4
Create Date: 2026-08-13 04:26:53.099884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6388e3d5a94'
down_revision = '3f8369638ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('voice_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('voice_name')
        batch_op.drop_column('avatar_key')

    # ### end Alembic commands ###
