"""add tokens_used and token_limit to user

Revision ID: e61683cda521
Revises: d6388e3d5a94
Create Date: 2026-08-13 10:40:03.340034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61683cda521'
down_revision = 'd6388e3d5a94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default нужен вручную — на проде уже есть зарегистрированные
    # пользователи, а NOT NULL колонка без дефолта на непустой таблице упадёт.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tokens_used', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('token_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_limit')
        batch_op.drop_column('tokens_used')

    # ### end Alembic commands ###
