"""add telegram_links and telegram_link_codes tables

Revision ID: 12f80e927e17
Revises: e027dc740312
Create Date: 2026-08-29 13:40:26.154651

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '12f80e927e17'
down_revision = 'e027dc740312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_link_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('telegram_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_chat_id'),
    sa.UniqueConstraint('user_id')
    )
    # Автогенерация Alembic также предлагала удалить таблицы
    # order/product/review/user/invite/shop — это не модели "Истока", они
    # не описаны ни в одной модели этого приложения (см. app/models.py) и,
    # судя по колонкам (wall_color, model_file, shelf_x...), относятся к
    # совсем другому проекту, у которого исторически общая база Postgres.
    # Намеренно не трогаем их — только новые таблицы Telegram-бота.


def downgrade():
    op.drop_table('telegram_links')
    op.drop_table('telegram_link_codes')
