"""Add comment field to SacredSource

Revision ID: 1fca3e816067
Revises: f1319d6eb053
Create Date: 2026-08-02 11:29:29.121338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fca3e816067'
down_revision = 'f1319d6eb053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacred_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sacred_sources', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
