"""Initial migration

Revision ID: f1319d6eb053
Revises: 
Create Date: 2026-08-01 06:00:04.934638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1319d6eb053'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=True)

    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('coverage', sa.String(length=255), nullable=True),
    sa.Column('delivery_time', sa.String(length=120), nullable=False),
    sa.Column('price_rub', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_rub', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sacred_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('belief', sa.Text(), nullable=False),
    sa.Column('allowed', sa.Text(), nullable=False),
    sa.Column('forbidden', sa.Text(), nullable=False),
    sa.Column('annual_visitors', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sacred_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sacred_sources_slug'), ['slug'], unique=True)

    op.create_table('water_brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('water_type', sa.String(length=120), nullable=False),
    sa.Column('mineralization_mg_l', sa.Integer(), nullable=True),
    sa.Column('volume_l', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('price_rub', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_brands')
    with op.batch_alter_table('sacred_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sacred_sources_slug'))

    op.drop_table('sacred_sources')
    op.drop_table('experiments')
    op.drop_table('equipment')
    op.drop_table('delivery_services')
    op.drop_table('books')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_slug'))

    op.drop_table('articles')
    # ### end Alembic commands ###
