"""add google_id to users

Revision ID: faecd55ec6d4
Revises: b51725cfaa19
Create Date: 2026-08-27 05:39:48.348018

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'faecd55ec6d4'
down_revision = 'b51725cfaa19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Автогенерация также предложила удалить таблицы invite/product/shop/
    # review/user/order — это чужие таблицы (от vr_shop), случайно
    # оказавшиеся в этой же БД, и они не описаны в моделях приложения.
    # Эту миграцию используем только для google_id — трогать их не нужно.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('google_id')
    # ### end Alembic commands ###
