"""player card number, blocking, support messages

Revision ID: c5ad6f0374b0
Revises: 7f443223c430
Create Date: 2026-08-15 14:09:51.490970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ad6f0374b0'
down_revision = '7f443223c430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender_is_admin', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('photo_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_messages_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.String(length=32), nullable=True))
        # server_default нужен, потому что колонка NOT NULL добавляется в
        # таблицу, где уже есть строки (существующие пользователи) — без
        # значения по умолчанию для них Postgres не примет NOT NULL.
        batch_op.add_column(
            sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('blocked_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('blocked_reason', sa.String(length=255), nullable=True))

    with op.batch_alter_table('wallet_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_number', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_requests', schema=None) as batch_op:
        batch_op.drop_column('card_number')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('blocked_reason')
        batch_op.drop_column('blocked_until')
        batch_op.drop_column('is_blocked')
        batch_op.drop_column('card_number')

    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_messages_user_id'))

    op.drop_table('support_messages')
    # ### end Alembic commands ###
