"""portfolio media

Revision ID: 4826cfa7e0f0
Revises: a239ce913c05
Create Date: 2026-08-07 18:08:38.568771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4826cfa7e0f0'
down_revision = 'a239ce913c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_media_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_media_user_id'))

    op.drop_table('portfolio_media')
    # ### end Alembic commands ###
