"""executor has_design_engineer flag

Revision ID: 5efdc059b392
Revises: ffd1506b1ef8
Create Date: 2026-08-05 05:35:48.595443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5efdc059b392'
down_revision = 'ffd1506b1ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'has_design_engineer', sa.Boolean(), nullable=False, server_default=sa.false(),
        ))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executor_profiles', schema=None) as batch_op:
        batch_op.drop_column('has_design_engineer')

    # ### end Alembic commands ###
