"""initial

Revision ID: 99c7a7721e13
Revises: 
Create Date: 2026-08-04 08:24:31.244011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99c7a7721e13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=160), nullable=False),
    sa.Column('name_uz_latin', sa.String(length=160), nullable=False),
    sa.Column('name_uz_cyrillic', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=160), nullable=False),
    sa.Column('name_uz_latin', sa.String(length=160), nullable=False),
    sa.Column('name_uz_cyrillic', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=120), nullable=False),
    sa.Column('name_uz_latin', sa.String(length=120), nullable=False),
    sa.Column('name_uz_cyrillic', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=160), nullable=False),
    sa.Column('name_uz_latin', sa.String(length=160), nullable=False),
    sa.Column('name_uz_cyrillic', sa.String(length=160), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=120), nullable=False),
    sa.Column('name_uz_latin', sa.String(length=120), nullable=False),
    sa.Column('name_uz_cyrillic', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('stir_inn', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('address_text', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('executor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_type', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stir_inn', sa.String(length=50), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('address_text', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('service_radius_km', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('executor_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('max_length_mm', sa.Integer(), nullable=True),
    sa.Column('max_diameter_mm', sa.Integer(), nullable=True),
    sa.Column('max_width_mm', sa.Integer(), nullable=True),
    sa.Column('max_height_mm', sa.Integer(), nullable=True),
    sa.Column('max_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['executor_id'], ['executor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('executor_id')
    )
    op.create_table('executor_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_type_id'], ['equipment_types.id'], ),
    sa.ForeignKeyConstraint(['executor_id'], ['executor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executor_capability_materials',
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['executor_capabilities.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('capability_id', 'material_id')
    )
    op.create_table('executor_capability_services',
    sa.Column('capability_id', sa.Integer(), nullable=False),
    sa.Column('service_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['executor_capabilities.id'], ),
    sa.ForeignKeyConstraint(['service_category_id'], ['service_categories.id'], ),
    sa.PrimaryKeyConstraint('capability_id', 'service_category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('executor_capability_services')
    op.drop_table('executor_capability_materials')
    op.drop_table('executor_equipment')
    op.drop_table('executor_capabilities')
    op.drop_table('executor_profiles')
    op.drop_table('customer_profiles')
    op.drop_table('cities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('service_categories')
    op.drop_table('regions')
    op.drop_table('materials')
    op.drop_table('equipment_types')
    # ### end Alembic commands ###
