"""payment methods, delivery, workload

Revision ID: a9b07cc47d45
Revises: 4826cfa7e0f0
Create Date: 2026-08-08 06:07:23.119274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9b07cc47d45'
down_revision = '4826cfa7e0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('constructor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_methods', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('workload', sa.Integer(), nullable=True))

    with op.batch_alter_table('executor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_methods', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('workload', sa.Integer(), nullable=True))

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_methods', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('delivery', sa.String(length=20), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_methods', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('payment_methods')

    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('delivery')
        batch_op.drop_column('payment_methods')

    with op.batch_alter_table('executor_profiles', schema=None) as batch_op:
        batch_op.drop_column('workload')
        batch_op.drop_column('payment_methods')

    with op.batch_alter_table('constructor_profiles', schema=None) as batch_op:
        batch_op.drop_column('workload')
        batch_op.drop_column('payment_methods')

    # ### end Alembic commands ###
